# Разогрев

## Задание 1

Иногда, когда нужно создавать много однотипных лямбда функций, еще удобнее будет создать функцию, которая будет их генерировать.

Реализуйте функцию ``mod_checker(x, mod=0)``, которая будет **возвращать лямбда функцию** от одного аргумента ``y``, которая будет возвращать ``True``, если остаток от деления ``y`` на ``x`` равен ``mod``, и ``False`` иначе.

Если в ``return`` вашей функции написано выражение, отличное от лямбда функции - задание считается проваленным

**Sample:**

```python
mod_3 = mod_checker(3)

print(mod_3(3)) # True
print(mod_3(4)) # False

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4)) # True
```

In [1]:
from collections.abc import Callable

def mod_checker(x: int, mod: int=0) -> Callable[[int], bool]:
    """
    Outer function returnes lambda-function.
    Lambda-function returnes True if y % x == mod,
                             False in the other case.

    Outer function:
    :param x: integer number
    :param mod: remainder of division, default=0
    :return: lambda-function

    Inner lambda-function:
    :param y: integer
    :return: bool
    """
    if x == 0:
        raise ZeroDivisionError("You can't divide by 0")

    return lambda y: True if y % x == mod else False

In [2]:
mod_3 = mod_checker(3)

print(mod_3(3))
print(mod_3(4))
print(mod_3(6))

True
False
True


In [3]:
mod_3_1 = mod_checker(3, 1)

print(mod_3_1(4))
print(mod_3_1(3))
print(mod_3_1(7))

True
False
True


# Numpy

In [4]:
import numpy as np

## Задание 2
Напишите функцию, которая принимает один аргумент - ``n``. Функция должна создать нампаевскую матрицу размером ``(n, n)`` и залить ее шахматным узором. Порядок узора не имеет значения, важен общий паттерн.

**Sample:**
```python
chess_maze(8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```



In [5]:
def chess_maze(n: int) -> np.array:
    """
    Function creates array witn checkered pattern.

    :param n: size of array
    :return: numpy array
    """
    # Initialize empty 2D array of given length
    arr = np.zeros((n, n), dtype=np.int8)
    # Fill with ones intersections of every second row (starting with 2-nd)
    # and every second column (starting with 1-st),
    # after that repeat it vice versa
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1

    return arr

In [6]:
print(chess_maze(8))
print()
print(chess_maze(3))
print()
print(chess_maze(2))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

[[0 1 0]
 [1 0 1]
 [0 1 0]]

[[0 1]
 [1 0]]


## Задание 3
Напишите функцию, которая принимает 2 аргумента ``arr`` и ``exclude_values``. ``arr`` - это одномерный нампаевский массив, в котором необходимо поменять знак всем числам (инвертировать), которые есть в массиве ``exclude_values``. Действия необходимо делать прямо в исходном массиве, не создавая копий.

**Sample:**
```python
#Исходный вектор 
arr = np.arange(10+1)
exclude_values = np.arange(4, 8)
 
my_func(arr, exclude_values)
array([ 0  1  2  3 -4 -5 -6 -7  8  9 10])
```

In [7]:
def sign_inversion(arr: np.array, exclude_values: np.array) -> np.array:
    """
    Function inverts signs of given numbers in the array.

    :param arr: initial array
    :param exclude_values: numbers that should be inverted
    :return: changed array
    """
    arr[np.in1d(arr, exclude_values)] *= (-1)

    return arr

In [8]:
arr = np.arange(10+1)
exclude_values = np.arange(4, 8)

sign_inversion(arr, exclude_values)

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [9]:
arr = np.random.randint(20, size=12)
print(arr)
exclude_values = np.random.randint(20, size=6)
print(exclude_values)

sign_inversion(arr, exclude_values)

[ 1 12  1  8  1  1 16 14 18  9  2 18]
[ 5 12  6  7 10  2]


array([  1, -12,   1,   8,   1,   1,  16,  14,  18,   9,  -2,  18])

## Задание 4
Напишите функцию, которая принимает одномерный положительный нампаевский массив и минимум 4 раза выводит на экран (функция ``print``) этот же массив, в котором у элементов оставлена только целая часть. Все >= 4 раза функция должна использовать разные методы для извлечения целой части.

**Sample:**
```python
#Исходный вектор 
arr = np.random.uniform(low=10, high=100,size=20)
#Исходный вектор arr:
arr
[99.54707368 49.26237526 80.50565073 10.10998238 16.39378916 60.64633657
 25.49637622 31.06574268 94.48636127 73.41204506 75.70638137 70.43830146
 72.28607422 40.59319738 57.85802554 35.39428061 55.25707514 48.00020145
 38.39449991 26.19085017]
 
my_func(arr)

[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99 49 80 10 16 60 25 31 94 73 75 70 72 40 57 35 55 48 38 26]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
```

В примере 5 выводов print из функции, просто чтобы были :)

In [10]:
def print_int(arr: np.array) -> None:
    """
    Function prints array with integer part of numbers.

    :param arr: array with float numbers
    :return: None
    """
    print(np.trunc(arr))
    print(arr // 1)
    print(np.modf(arr)[1])
    print(np.int32(arr))
    print(np.floor(arr))


arr = np.random.uniform(low=10, high=100,size=10)
print(arr)
print()
print_int(arr)

[99.03934264 49.58543049 65.68916195 94.78720201 10.46596413 41.59820244
 72.63583365 25.97110988 63.74615549 62.15314634]

[99. 49. 65. 94. 10. 41. 72. 25. 63. 62.]
[99. 49. 65. 94. 10. 41. 72. 25. 63. 62.]
[99. 49. 65. 94. 10. 41. 72. 25. 63. 62.]
[99 49 65 94 10 41 72 25 63 62]
[99. 49. 65. 94. 10. 41. 72. 25. 63. 62.]


## Задание 5
Напишите функцию, которая принимает два числа - ``N`` и ``p``. ``N`` - это размер стороны квадратной матрицы np.zeros, ``p`` - это количество индексов в матрице (p не превышает N*N), которые нужно заменить на случайные числа. Индексы и числа нужно выбирать случайно. Функция должна возвращать квадратную матрицу со стороной ``N``, в которой ровно ``p`` чисел заменены на случайные.

```python
my_func(N=6, p=4)

[[56.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [99.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 83.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   1.   0.]]
```

In [11]:
def change_array(n: int, p: int) -> np.array:
    """
    Function changes given number of elements in the array.

    :param n: size of array
    :param p: number of indices that should be changed
    :return: changed array
    """
    try:
        arr = np.zeros((n, n), dtype=np.int8).flatten()
        ind_list = np.arange(n * n)
        # Randomly choose given number of indices
        ind = np.random.choice(ind_list, size=p, replace=False)

        # Loop replaces given indices by random numbers
        for i in ind:
            arr[i] = np.random.randint(1, 100)
    except ValueError:
        print("Number of indices (p) can't be greater than n*n")

    return arr.reshape(n, n)

In [12]:
change_array(n=6, p=4)

array([[ 0,  0,  0,  0, 95,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0, 81, 54,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int8)

In [13]:
change_array(n=4, p=16)

array([[24, 31, 95,  1],
       [82, 81, 73, 21],
       [99, 75, 70, 75],
       [18,  2, 12,  1]], dtype=int8)

In [14]:
change_array(n=6, p=40)

Number of indices (p) can't be greater than n*n


# Pandas

In [15]:
import pandas as pd

# Задание 6

Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и четыре наблюдения в каждой колонке:

```
type value
B    18.

B    20.

C    10.

C    -10.
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

In [16]:
my_data = pd.DataFrame({
    'type': ['B', 'B', 'C', 'C'],
    'value': [18., 20, 10, -10]
})

display(my_data)
# Более информативно df.info() - размер 192 байта
display(my_data.info())
display(my_data.memory_usage())

type  value
0    B   18.0
1    B   20.0
2    C   10.0
3    C  -10.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   type    4 non-null      object 
 1   value   4 non-null      float64
dtypes: float64(1), object(1)
memory usage: 192.0+ bytes


None

Index    128
type      32
value     32
dtype: int64

In [17]:
my_data['type'] = my_data['type'].astype('category')

# Размер датафрейма увеличился
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    4 non-null      category
 1   value   4 non-null      float64 
dtypes: category(1), float64(1)
memory usage: 288.0 bytes


In [18]:
my_data['value'] = my_data['value'].astype('int64')

# Размер датафрейма не изменился
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    4 non-null      category
 1   value   4 non-null      int64   
dtypes: category(1), int64(1)
memory usage: 288.0 bytes


# Задание 7
Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и десять тысяч (10 000) наблюдений в каждой колонке. В колонке ``type`` должно быть 10 уникальных значений.

```python
my_data.shape
____________
(10000, 2)
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

Во сколько раз уменьшился размер исходного датафрейма после выполнения этих двух операций?

In [19]:
types = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

my_data = pd.DataFrame({
    'type': np.random.choice(types, size=10000),
    'value': np.random.uniform(10, 1000, size=10000)
})

my_data

type       value
0       E  421.979666
1       E  751.750327
2       I  758.751048
3       H  354.331069
4       D  485.684047
...   ...         ...
9995    A   98.506362
9996    C  583.070249
9997    A  553.320215
9998    G  924.220244
9999    G  834.397234

[10000 rows x 2 columns]

In [20]:
# Более информативно df.info()
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   type    10000 non-null  object 
 1   value   10000 non-null  float64
dtypes: float64(1), object(1)
memory usage: 156.4+ KB


In [21]:
my_data['type'] = my_data['type'].astype('category')

# Размер датафрейма уменьшился в 2 раза
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    10000 non-null  category
 1   value   10000 non-null  float64 
dtypes: category(1), float64(1)
memory usage: 88.4 KB


In [22]:
my_data['value'] = my_data['value'].astype('int64')

# Размер датафрейма дополнительно не изменился
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    10000 non-null  category
 1   value   10000 non-null  int64   
dtypes: category(1), int64(1)
memory usage: 88.4 KB


#### Для решения дальнейших задач мы будем использовать следующий датасет, загрузите его с помощью команды:

In [23]:
df = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat.csv')

In [24]:
df

V1    V2 V3   V4
0     2  13.0  B  1.0
1    -1   7.0  B  1.0
2     0  11.0  A  0.0
3     2  11.0  A  2.0
4     0  10.0  B -1.0
..   ..   ... ..  ...
495   1   8.0  A -1.0
496   3   8.0  A  1.0
497  -1  11.0  B  2.0
498   1  11.0  A  2.0
499   0   8.0  B  1.0

[500 rows x 4 columns]

Примечание: все операции с исходным датафреймом должны быть ``inplace``. То есть исходный датафрейм в переменной ``df`` **должен** измениться

# Задание 8

В переменную с именем subset_1 сохраните только первые 19 строк и только 1 и 3 колонку.

В переменную с именем subset_2 сохраните все строки кроме 2, 3 и 18 и только 2 и 4 колонку.

In [25]:
subset_1 = df.iloc[:19, [0, 2]]

subset_2 = df[
    (df.index != 1) 
    & (df.index != 2) 
    & (df.index != 17)
].iloc[:, [1, 3]]

# Задание 9

В переменную subset_3 сохраните только те наблюдения, у которых значения переменной V1 строго больше 0, и значение переменной V3  равняется 'A'.

В переменную  subset_4  сохраните только те наблюдения, у которых значения переменной V2  не равняются 10, или значения переменной V4 больше или равно 1.

In [26]:
subset_3 = df[
    (df['V1'] > 0) 
    & (df['V3'] == 'A')
]

subset_4 = df[
    (df['V2'] != 10) 
    | (df['V4'] >= 1)
]

# Задание 10
Добавьте следующие колонки в df:

1) V5 = V1 + V4
2) V6 = **натуральный** логарифм переменной V2

In [27]:
df['V5'] = df['V1'] + df['V4']
df.head(3)

V1    V2 V3   V4   V5
0   2  13.0  B  1.0  3.0
1  -1   7.0  B  1.0  0.0
2   0  11.0  A  0.0  0.0

In [28]:
df['V6'] = np.log(df['V2'])
df.head(3)

V1    V2 V3   V4   V5        V6
0   2  13.0  B  1.0  3.0  2.564949
1  -1   7.0  B  1.0  0.0  1.945910
2   0  11.0  A  0.0  0.0  2.397895

# Задание 11

Переименуйте колонки в df.

1) V1 -> session_value

2) V2 -> group

3) V3 -> time

4) V4 -> n_users

In [29]:
df.rename(columns = {
    'V1': 'session_value',
    'V2': 'group',
    'V3': 'time',
    'V4': 'n_users'
}, inplace=True
)

df.head(2)

session_value  group time  n_users   V5        V6
0              2   13.0    B      1.0  3.0  2.564949
1             -1    7.0    B      1.0  0.0  1.945910

# Задание 12
В датафрейме ``my_stat`` в колонке ``session_value`` замените все пропущенные значения на нули.

В колонке ``n_users`` замените все отрицательные значения на медианное значение переменной ``n_users`` (без учета отрицательных значений, разумеется).

In [30]:
my_stat = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat_1.csv')

In [31]:
my_stat

session_value  time group  n_users
0            0.0    12     B        9
1            NaN    11     A       -1
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            NaN    11     B        5
7            0.0     9     A        4
8            0.0     8     B      -11
9            0.0     9     A      -20

In [32]:
my_stat.loc[
    my_stat['session_value'].isna() == True,
    ['session_value']
] = 0

my_stat

session_value  time group  n_users
0            0.0    12     B        9
1            0.0    11     A       -1
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            0.0    11     B        5
7            0.0     9     A        4
8            0.0     8     B      -11
9            0.0     9     A      -20

In [33]:
median_n = my_stat[my_stat['n_users'] > 0]['n_users'].median()
my_stat.loc[
    my_stat['n_users'] < 0,
    ['n_users']
] = median_n

my_stat

session_value  time group  n_users
0            0.0    12     B        9
1            0.0    11     A        5
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            0.0    11     B        5
7            0.0     9     A        4
8            0.0     8     B        5
9            0.0     9     A        5