# Reversed integer

Вам дано число целого типа ``a``. Вам необходимо написать функцию, которая принимает это число на вход, а на выход выдает целое число, цифры в котором записаны в обратном порядке.


**Sample Input 1:**

``
a = 123
``

**Sample Output 1:**

``321``

**Sample Input 2:**

``
a = 120
``

**Sample Output 2:**

``21``

**Sample Input 3:**

``
-123
``

**Sample Output 3:**

``321``

In [1]:
def reverse_number(num: int) -> int:
    """
    Function retuns reverted integer.

    :param num: integer
    :return: reverted integer
    """
    # Remove negative sign from a number
    abs_num = abs(num)
    # Place last digit from number to reversed number
    reversed_num = abs_num % 10

    # Loop for cutting last digit from number 
    # and placing it to reversed number
    while True:
        abs_num //= 10
        if abs_num == 0: 
            break
        reversed_num = reversed_num * 10 + abs_num % 10

    return reversed_num

In [2]:
reverse_number(-230)

32

In [3]:
reverse_number(32600)

623

In [4]:
reverse_number(1234)

4321

# Empty square

Напишите функцию, которая принимает единственное число ``n: int``. Это число определяет длину стороны квадрата. Функция должна нарисовать квадрат из звездочек, при этом звездочки должны быть только на ребрах квадрата, центр должен быть выколот.

**Sample Input 1:**

``
n = 5
``

**Sample Output 1:**
```
* * * * *
*       *
*       *
*       *
* * * * *

```

In [5]:
def make_square(n: int):
    """
    Function prints empty square of `*`

    :param n: number of * in rows and columns
    :return: None
    """
    for i in range(n):
        for j in range(n):
            # Print * for all initial and last positions 
            if i == 0 or i == n-1 or j == 0 or j == n-1:
                print('* ', end='')
            # Print spaces for other positions
            else:
                print('  ', end='')
        print()

In [6]:
make_square(1)

* 


In [7]:
make_square(2)

* * 
* * 


In [8]:
make_square(3)

* * * 
*   * 
* * * 


In [9]:
make_square(5)

* * * * * 
*       * 
*       * 
*       * 
* * * * * 


In [10]:
make_square(10)

* * * * * * * * * * 
*                 * 
*                 * 
*                 * 
*                 * 
*                 * 
*                 * 
*                 * 
*                 * 
* * * * * * * * * * 


# Permutations

Вам дан массив с целыми числами ``nums``. Напишите функцию, которая принимает на вход данный массив и возвращает все возможные пермутации с данными числами. Возвращать массивы можно в любом порядке.

**Sample Input 1:**

``
nums = [1,2,3]
``

**Sample Output 1:**

``[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]``

**Sample Input 2:**

``
nums = [0,1]
``

**Sample Output 2:**

``[[0,1],[1,0]]``

**Sample Input 3:**

``
nums = [1]
``

**Sample Output 3:**

``[[1]]``

In [11]:
# Import permutation function
from itertools import permutations


def permutation(nums: list('int')) -> list('int'):
    """
    Function creates all possible permutations of the list of integers.

    :param nums: list of integers
    :return: list of list with all permutations 
    """
    # As permutation function returns list of tuple, 
    # change type of permutations into list
    perm_lst = list(map(list, permutations(nums)))

    return perm_lst

In [12]:
permutation([1, 2, 3])

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]

In [13]:
permutation([0, 1])

[[0, 1], [1, 0]]

In [14]:
permutation([1])

[[1]]

# Double factorial including only even numbers
Дано натуральное $N \leqslant 100$.  Выведите произведение всех чётных натуральных чисел, не превосходящих $N$.

In [15]:
def almost_double_factorial(n: int) -> int:
    """
    Function calculates double factorial including only even numbers.

    :param n: integer
    :return: double factorial including only even numbers 
    """
    # Condition for breaking recursion
    if n == 0 or n == 1: 
        return 1
    # For even number calculate normal double factorial
    if n % 2 == 0:
        return n * almost_double_factorial(n - 2)
    # For odd number reduce this number to get even one
    else:
        return (n-1) * almost_double_factorial(n - 2)

In [16]:
N = 25
N_double_fact = almost_double_factorial(N)
assert N_double_fact == 1961990553600, "Something is wrong! Please try again"

N = 100
N_double_fact = almost_double_factorial(N)
assert N_double_fact == \
34243224702511976248246432895208185975118675053719198827915654463488000000000000,\
"Something is wrong! Please try again"

In [17]:
almost_double_factorial(25)

1961990553600

In [18]:
almost_double_factorial(100)

34243224702511976248246432895208185975118675053719198827915654463488000000000000

# Sorting

Пусть у нас есть следующий список, в котором элементы -- tuple из строк:

``items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]``

Мы хотим отсортировать этот список по последней букве второго элемента каждого ``tuple``, т.е. получить такой список:

``sorted_items = [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]``.
Что нужно вставить вместо "###" в следующем выражении, чтобы получить сортировку?

``sorted_items = sorted(items, key=lambda x: ###)``

In [19]:
items = [('one', 'two'),
         ('three', 'four'),
         ('five', 'six'),
         ('string', 'a')
        ]

sorted_items = sorted(items, key=lambda item: item[1][-1])
                      
assert sorted_items == [('string', 'a'),
                        ('one', 'two'),
                        ('three', 'four'),
                        ('five', 'six')
                       ], "Something is wrong! Please try again"

In [20]:
sorted_items

[('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]

# String replacement

Вашей программе на вход подаются три строки ``s, a, b``, состоящие из строчных латинских букв.
За одну операцию вы можете заменить все вхождения строки ``a`` в строку ``s`` на строку ``b``.

Например, ``s = "abab", a = "ab", b = "ba"``, тогда после выполнения одной операции строка ``s`` перейдет в строку ``"baba"``, после выполнения двух и операций – в строку ``"bbaa"``, и дальнейшие операции не будут изменять строку ``s``.

Необходимо узнать, после какого минимального количества операций в строке ``s`` не останется вхождений строки ``a``. Если операций потребуется более 1000, выведите ``Impossible``.

Выведите одно число – минимальное число операций, после применения которых в строке ``s`` не останется вхождений строки ``a``, или ``Impossible``, если операций потребуется более 1000.

**Sample Input 1:**

``
ababa
a
b
``

**Sample Output 1:**

``1``

**Sample Input 2:**

``ababa
b
a``

**Sample Output 2:**

``1``

**Sample Input 3:**

``ababa
c
c``

**Sample Output 3:**

``0``

**Sample Input 4:**

``ababac
c
c``

**Sample Output 4:**

``Impossible``


In [21]:
def my_func(string: str, a_str: str, b_str: str) -> int or str:
    """
    Each loop replaces all occurrences of `a_str` by `b_str` in the string.
    Function calculates minimal number of loops to completely modify string.
    Completely modifying means that `a` is no longer in the modified string.

    :param string: initial string
    :param a_str: string that is needed to be replaced
    :param b_str: replacing string
    :return:  minimal number of loops to completely modify initial string
              or 'Impossible' in case of number of loops > 1000
    """
    count = 0
    s_modif = string

    while True:
        if count > 1000:
            return 'Impossible'
        elif a_str in s_modif:
            s_modif = s_modif.replace(a_str, b_str)
            count += 1
        else: break

    return count

In [22]:
my_func('abab', 'ab', 'ba')

2

In [23]:
my_func('ababac', 'c', 'c')

'Impossible'

In [24]:
my_func('abab', 'c', 'c')

0

# Cumulative sum
Дан массив $A[0,\ldots,N-1]$. Напишите функцию, принимающую один обязательный аргумент A и один опциональный аргумент ``erase``, по умолчанию равный 1. Возвратите массив $B[0,\ldots, N-1]$, где $B_i = A_0 + \ldots + A_{i}$ --- массив частичных сумм массива $A$, предварительно удалив из массива $B$ все элементы, равные erase. Постарайтесь сделать это за линейное время без использования Numpy.

In [25]:
def cumsum_and_erase(list_a: list('int'), erase: int=1) -> list['int']:
    """
    Function creates new list with cumulative sums of current and previous elements
    and returns list without elements that are equals to a given number (`erase`).

    :param list_a: initial list
    :param erase: number that is should be deleted from new list, default value=1
    :return:
    """
    list_b = []
    summa = 0

    # Loop creates list with cumulative sums
    for num in list_a:
        summa += num
        list_b.append(summa)

    # Delete numbers that are equal to `erase`
    list_b = list(filter(lambda x: x != erase, list_b))

    return list_b


A = [5, 1, 4, 5, 14]
B = cumsum_and_erase(A, erase=10)

assert B == [5, 6, 15, 29], "Something is wrong! Please try again"

In [26]:
A = [5, 1, 4, 5, 14]
B = cumsum_and_erase(A, erase=10)
B

[5, 6, 15, 29]

In [27]:
A = [0, 8, 0, 5, 14]
B = cumsum_and_erase(A, erase=8)
B

[0, 13, 27]

# Text processing
Дан список текстов, слова в которых разделены пробелами (можно считать, что знаков препинания нет). Часть слов является "мусорными": в них присутствуют цифры и спецсимволы. Отфильтруйте такие слова из каждого текста. Используйте функции ``str.split``, ``str.isalpha``, ``str.join``, а также [генератор filter](http://pythonicway.com/python-functinal-programming).

In [28]:
sentences = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']


def process(sentences: list('str')) -> list('str'):
    """
    Function filters out words containing non-alphabetic symbols.

    :param sentences: initial list of strings
    :return: list of sentences without non-alphabetic symbols
    """
    result = []

    for sentence in sentences:
        word_list = sentence.split()
        res = list(filter(lambda word: word.isalpha(), word_list))
        res = ' '.join(res)
        result.append(res)
    
    return result


assert process(sentences) == ['thousand devils', 'My name is', 'Room costs'], \
"Something is wrong! Please try again"

In [29]:
sentences = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']
process(sentences)

['thousand devils', 'My name is', 'Room costs']

# Hamming distance

Вам даны две строки, ``a`` и ``b`` одинаковой длины. Необходимо посчитать расстояние Хэмминга между ними, которое определяется как количество символов, которые не совпадают между двумя строками в одинаковой позиции.

**Sample Input 1:**

```
a = 'AGCT'
b = 'ACGT'
hamming(a, b)
```

**Sample Output 1:**

``2``

In [30]:
def hamming(str_a: str, str_b: str) -> int:
    """
    Function calculates Hamming distance.

    :param str_a: first string
    :param str_b: second string
    :return: Hamming distance
    """
    count = 0

    for a, b in zip(str_a, str_b):
        if a != b:
            count += 1

    return count


assert hamming("AGCT", "ACGT") == 2

In [31]:
a = 'AGCT'
b = 'ACGT'
hamming(a, b)

2

In [32]:
a = 'karolin' 
b = 'kathrin'
hamming(a, b)

3

In [33]:
a = '1234'
b = '0000'
hamming(a, b)

4

# Numpy

In [34]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [35]:
# Для генерации матриц используем фукнцию random -- 
# она используется для генерации случайных объектов 
# функция sample создает случайную выборку. 
# В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
print(f'Размерность матрицы а: {a.ndim}')
print(f'Размерность матрицы b: {b.ndim}')
print(f'Количество строк и столбцов матрицы а: {a.shape}')
print(f'Количество строк и столбцов матрицы b: {b.shape}')
print()
# ========
print()
print(a)
print(b)

Размерность матрицы а: 2
Размерность матрицы b: 2
Количество строк и столбцов матрицы а: (100, 100)
Количество строк и столбцов матрицы b: (100, 100)


[[0.65005918 0.47189801 0.62948346 ... 0.02390339 0.49032301 0.13567913]
 [0.87448659 0.41788004 0.79920282 ... 0.4738236  0.60193605 0.51848742]
 [0.61970755 0.29098938 0.4655297  ... 0.76533072 0.68786419 0.29446967]
 ...
 [0.76751864 0.21589858 0.39055688 ... 0.90085301 0.64817495 0.54579439]
 [0.01065376 0.15795177 0.54790127 ... 0.64992555 0.30524403 0.21837619]
 [0.785398   0.29721307 0.94916897 ... 0.63629704 0.85626337 0.59450278]]
[[0.25841533 0.97350727 0.7093045  ... 0.94945034 0.40375025 0.78347894]
 [0.70023731 0.41078075 0.31785592 ... 0.55772565 0.39918143 0.56726988]
 [0.71010604 0.42678553 0.07742241 ... 0.79365432 0.64832947 0.41563908]
 ...
 [0.89449283 0.03220215 0.41295501 ... 0.04872091 0.42456784 0.65823846]
 [0.66213453 0.6132235  0.93952894 ... 0.00909376 0.621482   0.47176026]
 [0.04710773 0.94561771 0.61972673

In [36]:
def mult(list_a: list('int'), list_b: list('int')) -> list('int'):
    """  
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy 
    (может помочь функция zip)

    :param list_a: list of "size" lists, each contains "size" floats --- 
       первая матрица-аргумент
    :param list_b: list of "size" lists, each contains "size" floats --- 
       вторая матрица-аргумент
    :return: list of "size" lists, each contains "size" floats ---
       матрица, являющаяся результатом умножения матриц a и b
    """
    list_c = []

    for row_a, row_b in zip(list_a, list_b):
        row_c = []
        for a, b in zip(row_a, row_b):
            row_c.append(a * b)
        list_c.append(row_c)

    return list_c


a = [[3, 4, 2],
     [2, 5, 3], 
     [2, 4, 3]
    ]
b = [[2, 5, 3],
     [1, 3, 2], 
     [3, 2, 4]
    ]

mult(a, b)

[[6, 20, 6], [2, 15, 6], [6, 8, 12]]

In [37]:
def np_mult(arr_a: np.array, arr_b: np.array) -> np.array:
    """  
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy.

    :param arr_a: np.array[size, size] --- первая матрица-аргумент
    :param arr_b: np.array[size, size] --- вторая матрица-аргумент
    :return: np.array[size, size] --- матрица, 
        являющаяся результатом умножения матриц a и b
    """
    return arr_a * arr_b


c = np.array([[3, 4, 2],
              [2, 5, 3], 
              [2, 4, 3]
             ], dtype=np.int16
            )
d = np.array([[2, 5, 3],
              [1, 3, 2],
              [3, 2, 4]
             ], dtype=np.int16
            )

np_mult(c, d)

array([[ 6, 20,  6],
       [ 2, 15,  6],
       [ 6,  8, 12]], dtype=int16)

In [41]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 0 ns
Wall time: 0 ns


In [42]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(c, d)

CPU times: total: 0 ns
Wall time: 0 ns


In [43]:
# проверим корректность
assert np.allclose(np.array(M1), M2)